---
docker_edition: "ce"
docker_apt_release_channel: "stable"
docker_apt_arch: "{{ ansible_architecture | replace('aarch64', 'arm64') | replace('x86_64', 'amd64') }}"
docker_apt_repository: >-
  deb [arch={{ docker_apt_arch }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
  https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}
docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
docker_apt_keyring: /usr/share/keyrings/docker-archive-keyring.gpg